{
    Вид диаграммы: | ^ Круговая диаграмма ^ | Детализация: | ^ Товарная группа ^
    .
    !ifndef BUDGET_DISTRIBUTION
        <u>Распределение бюджета</u> | * | <u>Распределение заказов</u> | *
    !else
        <u>Распределение бюджета</u> | * | * | *
    !endif
    {+ <- Изображение выбранной
        пользователем диаграммы
        по данным бюджета -> 
    !ifndef BUDGET_DISTRIBUTION
        }  | * | {+ <- Изображение выбранной
            пользователем диаграммы
            по данным заказов -> 
        }  | *
    !else
        }  | * | * | *
    !endif
}