{
    {
        !include wf_common_filter.iuml

        Магазин: | ^ "Женский каприз" ^ | . | .
        .
    
        {# 
            <u>Отдел</u>
            Аксессуары
            Обувь
            <b>Одежда</b>
        } | {#
            <u>Товарная группа</u>
            Детская одежда
            Женская одежда
            Мужская одежда
            Одежда для беременных
        } | {#
            <u>Укрупн. подгруппа</u>
            Белье
            Верхняя одежда
            Платье
            Чулочно-носочные
        } | {#
            <u>Товарная подгруппа</u>
            Бальное платье
            Вечернее платье
            Летнее платье
            Свадебное платье
        }
    }
    [Обновить отчет]
}