{
    {
        !include wf_common_filter.iuml
        Торговая марка: | ^ Bogner ^ | {#
            <u>Отдел</u>
            Аксессуары
            Обувь
            <b>Одежда</b>
        } | {#
            <u>Товарная группа</u>
            <b>Женская одежда</b>
            Мужская одежда
        }
    }
    [Обновить отчет]
}