{#
    <u>Отдел</u> |  <u>Товарная группа</u> | <u>Валюта закупки</u> | <u>Бюджет закупки</u> | <u>Доля в бюджете уровня, %</u>
    Одежда | <Все> | Евро | 5000 | 53
    Одежда | Детская одежда | Евро | 1000 | 20
    Одежда | Женская одежда | Евро | 2000 | 40
    Одежда | Мужская одежда | Евро | 1500 | 30
    Одежда | Одежда для беременных | Евро | 500 | 10
} | * | * | *
