{#
    <u>Наименование</u> | <u>Артикул</u> | <u>Цвет</u> | <u>Длина, ширина</u> | <u>Заказано</u> | <u>На сумму</u> | <u>В валюте</u>
    Платье без рукавов | scrigno | т сер | Миди | 4 | 1100 | Евро
    Платье с коротким рукавом | fiamma | голуб | Миди | 4 | 900 | Евро
} | * | * | *
