{#
    <u>Отдел</u> |  <u>Товарная группа</u> |  <u>Укрупн. подгруппа</u> |  <u>Товарная подгруппа</u> | <u>Принадлежность</u> | <u>Наименование</u> | <u>Валюта закупки</u> | <u>Бюджет закупки</u> | <u>Сумма заказов</u>
    <i>Одежда</i> | <i>Женская одежда</i> | <i><Все></i> | <i><Все></i> | <i><Все></i> | <i><Все></i> | <i>Евро</i> | <i>2000</i> | <i>2500</i>
    <b>Одежда</b> | <b>Женская одежда</b> | <b>Платье</b> | <b>Вечерние</b> | <b>Плечевая</b> | <b>Платье без рукавов</b> | <b>Евро</b> | . | <b>1100</b>
    <b>Одежда</b> | <b>Женская одежда</b> | <b>Платье</b> | <b>Летние</b> | <b>Плечевая</b> | <b>Платье с коротким рукавом</b> | <b>Евро</b> | . | <b>900</b>
    Одежда | Женская одежда | Платье | Летние | Плечевая | Платье на бретельках | Евро | . | 500
} | * | * | *
